[package]
name = "mukti-metadata"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
serde = { version = "1", features = ["derive"] }
semver = { version = "1", features = ["serde"] }
