[package]
name = "mukti-bin"
description = "Command to update release metadata"
version = "0.5.2"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
atomicwrites = "0.3.1"
camino = "1.1.1"
clap = { version = "4.0.24", features = ["derive"] }
color-eyre = { version = "0.6.2", default-features = false }
serde_json = "1.0.87"
semver = "1.0.14"
mukti-metadata = { path = "../mukti-metadata" }
