[package]
name = "mukti-bin"
description = "Command to update release metadata"
version = "0.5.2"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
atomicwrites = "0.3.1"
camino = "1.0.9"
clap = { version = "3.2.15", features = ["derive"] }
color-eyre = { version = "0.6.1", default-features = false }
serde_json = "1.0.81"
semver = "1.0.10"
mukti-metadata = { path = "../mukti-metadata" }
